apiVersion: v1
kind: Secret
metadata:
  name: dummy-secret
  namespace: default
type: Opaque
data:
  username: ZHVtbXl1c2Vy  # "dummyuser" base64-encoded
  password: ZHVtbXlwYXNz  # "dummypass" base64-encoded
